<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="5CG6332Q3H" name="Mobile Test" tests="1" failures="0" timestamp="31 Aug 2017 07:44:56 GMT" time="120.073" errors="0">
  <testcase name="@BeforeMethod launchApp" time="0.0" classname="com.ctli.it.mobiletestcase.Ghost_MobileScenario">
    <failure type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException" message="The local appium server has not been started. The given Node.js executable: C:\Program Files (x86)\Appium\node.exe Arguments: [C:\Program Files (x86)\Appium\node_modules\appium\bin\appium.js, --port, 4723, --address, 0.0.0.0, --log, G:\Final_10Night\CTLI_HAMPS\.\AppiumServerlog.txt] 
Process output: [31merror[39m: Couldn&amp;apos;t start Appium REST http interface listener. Requested port is already in use. Please make sure there&amp;apos;s no other instance of Appium running already.

">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files (x86)\Appium\node.exe Arguments: [C:\Program Files (x86)\Appium\node_modules\appium\bin\appium.js, --port, 4723, --address, 0.0.0.0, --log, G:\Final_10Night\CTLI_HAMPS\.\AppiumServerlog.txt] 
Process output: [31merror[39m: Couldn't start Appium REST http interface listener. Requested port is already in use. Please make sure there's no other instance of Appium running already.


	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:155)
	at com.ctli.it.lib.AppiumServerStarting.appiumStart(AppiumServerStarting.java:23)
	at com.ctli.it.lib.TestNgInitialization.launchApp(TestNgInitialization.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://0.0.0.0:4723/wd/hub/status] to be available after 120002 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:107)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:115)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:142)
	... 17 more
Caused by: com.google.common.util.concurrent.UncheckedTimeoutException: java.util.concurrent.TimeoutException
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:143)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:80)
	... 19 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:130)
	... 20 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod launchApp -->
  <testcase name="@AfterMethod closeApp" time="0.0" classname="com.ctli.it.mobiletestcase.Ghost_MobileScenario">
    <skipped/>
  </testcase> <!-- @AfterMethod closeApp -->
  <testcase name="Mobile_Scenario" time="0.001" classname="com.ctli.it.mobiletestcase.Ghost_MobileScenario">
    <skipped/>
  </testcase> <!-- Mobile_Scenario -->
</testsuite> <!-- Mobile Test -->
